version: 0.2

phases:
  install:
    commands:
      - echo Fetching dependencies
      - curl https://glide.sh/get | sh
      - glide install
  build:
    commands:
      - echo Build started on `date`
      - go build -o bin/application ./cmd/imascg
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - bin/application
    - .ebextensions/**/*
